/* eslint-disable */

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BrainlyComponentGenerator {
  /**
   * The prompting profile to use (determines which other options are relevant).
   */
  promptsProfile?: 'basic' | 'sample' | 'advanced';
  /**
   * Library name
   */
  library?: string;
  /**
   * Component name
   */
  name?: string;
  /**
   * Component props definition
   */
  props?: string;
  /**
   * Component events definition
   */
  events?: string;
  /**
   * Component copy/text content
   */
  copy?: string;
  /**
   * Component styles definition
   */
  styles?: string;
  /**
   * Whether to generate tests and test configuration
   */
  tests?: boolean | string;
  /**
   * Whether to generate Storybook stories
   */
  storybook?: boolean | string;
  /**
   * Whether to reexport the component
   */
  reexport?: boolean | string;
  /**
   * Style guide components to use
   */
  sgComponents?: string;
  /**
   * Data test ID for testing
   */
  dataTestid?: string;
}
