name: Pull Request Checks

on:
  pull_request:
    branches:
      - master
      - alpha-*

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: '18.20.0'
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
      - name: Restore cached npm dependencies
        uses: actions/cache/restore@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3
        with:
          path: node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Cache npm dependencies
        uses: actions/cache/save@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3
        with:
          path: node_modules
          key: npm-dependencies-${{ hashFiles('pnpm-lock.yaml') }}
      - uses: nrwl/nx-set-shas@0e2d18b530b83b68263ff7b74e46b1ba300c83fc # v3
      - run: git branch --track master origin/master
      - name: Set NX_BASE and NX_HEAD
        run: |
          echo "NX_BASE=$(git merge-base origin/master HEAD)" >> $GITHUB_ENV
          echo "NX_HEAD=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Lint
        run: pnpm nx affected --target=lint --parallel=3

      # region test
      - run: pnpm nx run packages-gene:test
      - run: pnpm nx run packages-gene-next:test
      - run: pnpm nx run packages-gene-tools:test
      - run: pnpm nx run packages-gene-apollo:test
      - run: pnpm nx run assets:test
      - run: pnpm nx run packages-gene-sentry:test
      - run: pnpm nx run translations:test
      - run: pnpm nx run docs-docs-site:test
      - run: pnpm nx run e2e-testing-providers:test
      # endregion

      - name: Build
        run: pnpm nx affected --target=build --parallel=3
